### ISSUE TITLE
Trouble loading hosted service on useboomerang.io

### ISSUE THREAD

**Issue by dirtybits** [boomerang-io/useboomerang.io#47]
**Describe the bug**
When attempting to try out Boomerang Flow on the hosted app, after sign in with Github I get an error after loading.

1) Go to https://www.useboomerang.io/
2) Click on Try Me button taking you to https://try.useboomerang.io/flow/apps/flow
3) It brings github up to sign in, after that it either spins indefinitely or takes you to the page attached.
[Boomerang](https://user-images.githubusercontent.com/28834908/142504003-7493fb6e-3da3-4a60-a9e6-0f76032225c8.png)
4) viewing status brings me to a 403 page

**Expected behavior**
Page load.

**Screenshots**
[Boomerang](https://user-images.githubusercontent.com/28834908/142504003-7493fb6e-3da3-4a60-a9e6-0f76032225c8.png)

**Environment**
- OS: (Linux) Manjaro 21.1.6 Pahvo
- Browser: Chrome, Firefox

**Comment by tlawrie** [comment]
Thanks for raising the issue @dirtybits. We will look into it

**Comment by tlawrie** [comment]
Hi @dirtybits, apologies for this taking a while. The current environment is sponsored by IBM and we are working through the logistics. In the meantime you can also get free access through flowabl.io if that is something you want to check out.

**Comment by tlawrie** [comment]
This is now confirmed as resolved and hosted on GKE by Flowabl.io
