### ISSUE TITLE
Images can't display because of incorrect file names

### ISSUE THREAD

**Issue by digglife** [boomerang-io/useboomerang.io#50]
**Describe the bug**

Some of the images in the documentation can not be displayed because the file names in markdown are not correct.

**To Reproduce**

Example: https://www.useboomerang.io/docs/boomerang-flow/3.4.1/getting-to-know/triggers
The image for configure tab can't be displayed.

**Expected behavior**
Images are loaded correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/1468378/145075070-09e00109-1a44-4ff6-b06e-3b906d4123b5.png)

**Additional context**

a throwaway bash script for finding incorrect image filenames in markdown.

```bash
grep -E -i -r --include '*.md' '\.(png|svg)' . | awk -F':' '{print $2}' | gsed -E 's/.*\(\.?\/.*\/(.*\.(png|svg))\).*/\1/g' | sort | uniq | while read -r i;do
    find . -name "$i" | grep -q . || echo "$i" 
done
```

**Comment by timrbula** [comment]
Fixed with #51
